Traceback (most recent call last):
  File "c:\Users\434386\.conda\envs\jupyter_books\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\Users\434386\.conda\envs\jupyter_books\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\Users\434386\.conda\envs\jupyter_books\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\Users\434386\.conda\envs\jupyter_books\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\Users\434386\.conda\envs\jupyter_books\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\Users\434386\.conda\envs\jupyter_books\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "c:\Users\434386\.conda\envs\jupyter_books\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\Users\434386\.conda\envs\jupyter_books\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
pd.DataFrame([['hi', 'there'], ['this', 'is'], ['a', 'DataFrame']], columns=['Word A', 'Word B'])
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[6], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      2[0m pd[38;5;241m.[39mDataFrame([[[38;5;124m'[39m[38;5;124mhi[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mthere[39m[38;5;124m'[39m], [[38;5;124m'[39m[38;5;124mthis[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mis[39m[38;5;124m'[39m], [[38;5;124m'[39m[38;5;124ma[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mDataFrame[39m[38;5;124m'[39m]], columns[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mWord A[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mWord B[39m[38;5;124m'[39m])

[1;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

